# This file contains values from Cookiecutter

default_context:
  project_name: "django-query-capture"
  project_description: "Awesome `django-query-capture` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "AsheKR"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "ashekr"
  email: "tech@ashe.kr"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
