site_name: django-query-capture
site_url: https://ashekr.github.io/django-query-capture/
repo_url: https://github.com/AsheKR/django-query-capture

nav:
    - Home:
      - Overview: index.md
      - Settings: home/settings.md
      - How to Customize Presenter: home/customize_presenter.md
    - API Guide:
        - Capture Query: api_guide/capture_query.md
        - Presenter: api_guide/presenter.md
        - Test Util: api_guide/test_util.md
    - Code Reference: reference/
    - Development:
      - Contributing: contributing.md
      - Code of Conduct: code_of_conduct.md
      - Coverage report: coverage.md
      - License: license.md

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - navigation.tabs
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
- admonition:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite:
- pymdownx.snippets:
    check_paths: true
- pymdownx.details:
- pymdownx.superfences:
- toc:
    permalink: "¤"
- tables:

plugins:
- git-revision-date-localized:
    exclude:
      - reference/*
      - coverage.md
- autorefs:
- gen-files:
    scripts:
      - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- search:
- coverage:
- section-index:
- mkdocstrings:
    handlers:
      python:
        setup_commands:
          - import os
          - import sys
          - import django
          - sys.path.append("django_query_capture")
          - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
          - django.setup()
        selection:
          new_path_syntax: yes
    watch:
    - django_query_capture

extra_css:
- css/mkdocstrings.css
